### ISSUE TITLE
Add example usage

### ISSUE THREAD

**Issue by chasevida** [adrianlee44/lorax#1]
Hey, this looks like a nice module but I have a few questions.
1. I'm not exactly sure how lorax is meant to consume the configurations mentioned in the read me? I tried passing a file path but that did not seem to work.
2. Do you have to pass in a tag (does it default to all without one)?
3. Does this run on a local repo (I tried this but I get no output other than the tag name in the `changelog.md` file)?

I realise there is example usage but for some reason I can't seem to get it to operate based on that.

Thanks.

**Comment by chasevida** [comment]
Strange thought I'd try this out again and I still get no actual output. It always says `Parsed 0 commit(s)`.

**Comment by adrianlee44** [comment]
Is your repository pubic where I will be able to clone it?

I have been updating the code recently and would love to fix this bug.

**Comment by chasevida** [comment]
Hey no problem. I just created one here [chasevida/lorax-trial-n-error ](https://github.com/chasevida/lorax-trial-n-error ).

What I've since noticed is that actually it's actually two issues I've run in to.

1. The program does not parse any commits until the repo is available on github. I was testing this locally and once I pushed it live it began parsing commits. This may intended behaviour but it's confused me up until now. If it is how it operates it may be helpful to write this into the docs.
2. When it did parse the commit history it seemed to ignore the version option and only parse commits for the latest release. You can see this in the generated change logs which all have the same content but for which I parsed a different tag version:
    * [CHANGELOG-0.1.0](https://github.com/chasevida/lorax-trial-n-error/blob/master/CHANGELOG-0.1.0.md)
    * [CHANGELOG-0.2.0](https://github.com/chasevida/lorax-trial-n-error/blob/master/CHANGELOG-0.2.0.md)
    * [CHANGELOG](https://github.com/chasevida/lorax-trial-n-error/blob/master/CHANGELOG.md) - *v0.3.0*

Hope this helps. I may just be misunderstanding how it operates and have made an mistake somewhere, if so let me know.

Thanks :)

**Comment by adrianlee44** [comment]
Thank you so much for helping out. The two points you brought up in the previous comment are both bugs and not intended behavior.

I have created two separate issues (#2, #3) to better track them

Thanks.

**Comment by chasevida** [comment]
Awesome, glad I could help :)
